# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='descripition',
            new_name='description',
        ),
    ]
